/** @format */

import type { Metadata } from "next";
import { Montserrat, Inter } from "next/font/google";
import "./globals.css";

const monteserrat = Montserrat({
    subsets: ["latin-ext"],
    weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
    title: "Soracert admin",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={monteserrat.className}>{children}</body>
        </html>
    );
}
